auth:
  auth-memory:
    users:
      foo:
        name: test
        password: test
      bar:
        name: test
        password: test
store:
  memory:
    limit: 1000
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $anonymous
    publish: $anonymous
  '**':
    access: $anonymous
    publish: $anonymous
middlewares:
  audit:
    enabled: true
logs:
 - {type: stdout, format: pretty, level: warn}